name: Say Hello

on:
  push:
    branches:
      - main  # or replace with your target branch

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, world!"
